export const COUNTRIES = [
  { value: 'España', label: 'España' },
  { value: 'Reino Unido', label: 'Reino Unido' },
  { value: 'Canadá', label: 'Canadá' },
  { value: 'Estados Unidos', label: 'Estados Unidos' },
  { value: 'México', label: 'México' },
  { value: 'Belice', label: 'Belice' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Panamá', label: 'Panamá' },
  { value: 'Antigua y Barbuda', label: 'Antigua y Barbuda' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Granada', label: 'Granada' },
  { value: 'Haití', label: 'Haití' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'República Dominicana', label: 'República Dominicana' },
  { value: 'San Cristóbal y Nieves', label: 'San Cristóbal y Nieves' },
  { value: 'San Vicente y las Granadinas', label: 'San Vicente y las Granadinas' },
  { value: 'Santa Lucía', label: 'Santa Lucía' },
  { value: 'Trinidad y Tobago', label: 'Trinidad y Tobago' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Brasil', label: 'Brasil' },
  { value: 'Chile', label: 'Chile' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Perú', label: 'Perú' },
  { value: 'Surinam', label: 'Surinam' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Venezuela', label: 'Venezuela' },
].sort((a, b) => a.label.localeCompare(b.label)); // UX Extra: Ordenados alfabéticamente de forma automática