// Rubros / industrias para el registro de empresa.
export const INDUSTRY_OPTIONS = [
  'Tecnología / Software',
  'Telecomunicaciones',
  'Salud / Medicina',
  'Educación',
  'Finanzas / Banca',
  'Seguros',
  'Comercio / Retail',
  'E-commerce',
  'Manufactura / Industria',
  'Construcción',
  'Inmobiliaria',
  'Turismo / Hostelería',
  'Gastronomía / Restaurantes',
  'Transporte / Logística',
  'Marketing / Publicidad',
  'Medios / Comunicación',
  'Arte / Diseño / Entretenimiento',
  'Consultoría / Servicios profesionales',
  'Legal / Jurídico',
  'Recursos Humanos',
  'Agricultura / Agroindustria',
  'Energía / Minería',
  'Automotriz',
  'Alimentos y Bebidas',
  'Organizaciones sin fines de lucro',
  'Gobierno / Sector público',
  'Otro',
].map((name) => ({ value: name, label: name }))
